export const routes = {
  landing: "/",
  home: "/home",
  login: "/login",
  signup: "/signup",
  checkout: "/checkout",
  productDetails: "/product/:id",
  ads: "/ads",
  homepage:"/homepage",
  aboutus:"/aboutus",
  contactus:"/contactus",
  pendingproductdetails: "/pendingproduct/:id",
  logout: "/logout",
  users: "/users",
  profile: "/profile",
  orders: "/orders",
  revenue:"/revenue",
  chats:"/chats",
};
